### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by xItzDiamondx** [GrahamSH-LLK/site#22]
I like how you listed all your github repos on your website. How did you do that?

**Comment by GrahamSH-LLK** [comment]
> I like how you listed all your github repos on your website. How did you do that?

\*magic\* and cool code I stole from @eggsy. Look at `pages/index.vue` and the `Repo` and `Skeleton` components

**Comment by xItzDiamondx** [comment]
First off, am I allowed to use this, second off, what do you mean by repo and skeleton

**Comment by xItzDiamondx** [comment]
And do you want to collaborate on something?

**Comment by GrahamSH-LLK** [comment]
> First off, am I allowed to use this, second off, what do you mean by repo and skeleton

Sure! Repo and Skeleton are components in the components/ folder.



> And do you want to collaborate on something?

What?

**Comment by xItzDiamondx** [comment]
Dunno, whatever you think is nice. Also, thanks

**Comment by GrahamSH-LLK** [comment]
> Dunno, whatever you think is nice. Also, thanks. And how do you like, get custom domain names for gh pages?

You have to buy a domain

**Comment by xItzDiamondx** [comment]
Anyway, do you want to collab
