### ISSUE TITLE
Good Website

### ISSUE THREAD

**Issue by ZI-Youtuber** [GrahamSH-LLK/site#23]
You have made a epic website.

Can you tell me how you made it?

**Comment by GrahamSH-LLK** [comment]
Nuxt + tailwind + time + tailwind ui + effort + coding + copying + time

**Comment by ZI-Youtuber** [comment]
is your main code in index.html?

**Comment by GrahamSH-LLK** [comment]
> is your main code in index.html?

No, I don't have an index.html that I write. My pages are statically built using Nuxt. Take a look at https://nuxtjs.org. I use Tailwind CSS for all of my css (https://tailwindcss.com). The `pages/` directory is a good place to start. That's where all of my pages are stored. `index.vue` is my main page.

**Comment by ZI-Youtuber** [comment]
I see

**Comment by ZI-Youtuber** [comment]
You must of worked hard in making that website

**Comment by ZI-Youtuber** [comment]
Can I join that organization called Bijou.js pls?

**Comment by retronbv** [comment]
> Can I join that organization called Bijou.js pls?

Please stop
